rvm:
  - '1.9.3'
  - '2.0.0'
  - '2.1.2'
  - '2.2.2'

gemfile:
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x

notifications:
  email: false
